export const RANGE_SITUATION = {
  OPEN_RAISE_FI: 'Open Raise FI',
  ISOLATE: 'Isolate',
  SMALL_BLINDS_DEFENCE: 'Small blinds defence',
  BIG_BLINDS_DEFENCE: 'Bigblinds defence',
  BLINDS_DEFENCE_VS_4BET: 'Blinds defence vs 4bet',
  THREE_BET_IP: '3Bet IP',
  DEFENCE_VS_THREE_BET_IP: 'Defence vs 3Bet IP',
  DEFENCE_VS_THREE_BET_OOP: 'Defence vs 3Bet OOP',
} as const

export type RangeSituation = (typeof RANGE_SITUATION)[keyof typeof RANGE_SITUATION]

export const RANGE_SITUATION_ORDER: readonly RangeSituation[] = [
  RANGE_SITUATION.OPEN_RAISE_FI,
  RANGE_SITUATION.ISOLATE,
  RANGE_SITUATION.SMALL_BLINDS_DEFENCE,
  RANGE_SITUATION.BIG_BLINDS_DEFENCE,
  RANGE_SITUATION.BLINDS_DEFENCE_VS_4BET,
  RANGE_SITUATION.THREE_BET_IP,
  RANGE_SITUATION.DEFENCE_VS_THREE_BET_IP,
  RANGE_SITUATION.DEFENCE_VS_THREE_BET_OOP,
]
